package com.ahmer.accounts.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(color = 0xFFA14000)
val md_theme_light_onPrimary = Color(color = 0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(color = 0xFFFFDBCC)
val md_theme_light_onPrimaryContainer = Color(color = 0xFF351000)
val md_theme_light_secondary = Color(color = 0xFFBA1A20)
val md_theme_light_onSecondary = Color(color = 0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(color = 0xFFFFDAD6)
val md_theme_light_onSecondaryContainer = Color(color = 0xFF410003)
val md_theme_light_tertiary = Color(color = 0xFF875300)
val md_theme_light_onTertiary = Color(color = 0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(color = 0xFFFFDDB9)
val md_theme_light_onTertiaryContainer = Color(color = 0xFF2B1700)
val md_theme_light_error = Color(color = 0xFFBA1A1A)
val md_theme_light_errorContainer = Color(color = 0xFFFFDAD6)
val md_theme_light_onError = Color(color = 0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(color = 0xFF410002)
val md_theme_light_background = Color(color = 0xFFFFFBFF)
val md_theme_light_onBackground = Color(color = 0xFF2C1700)
val md_theme_light_surface = Color(color = 0xFFFFFBFF)
val md_theme_light_onSurface = Color(color = 0xFF2C1700)
val md_theme_light_surfaceVariant = Color(color = 0xFFF4DED5)
val md_theme_light_onSurfaceVariant = Color(color = 0xFF52443D)
val md_theme_light_outline = Color(color = 0xFF85736C)
val md_theme_light_inverseOnSurface = Color(color = 0xFFFFEEE0)
val md_theme_light_inverseSurface = Color(color = 0xFF482900)
val md_theme_light_inversePrimary = Color(color = 0xFFFFB694)
val md_theme_light_shadow = Color(color = 0xFF000000)
val md_theme_light_surfaceTint = Color(color = 0xFFA14000)
val md_theme_light_outlineVariant = Color(color = 0xFFD7C2BA)
val md_theme_light_scrim = Color(color = 0xFF000000)

val md_theme_dark_primary = Color(color = 0xFFFFB694)
val md_theme_dark_onPrimary = Color(color = 0xFF571F00)
val md_theme_dark_primaryContainer = Color(color = 0xFF7B2F00)
val md_theme_dark_onPrimaryContainer = Color(color = 0xFFFFDBCC)
val md_theme_dark_secondary = Color(color = 0xFFFFB3AC)
val md_theme_dark_onSecondary = Color(color = 0xFF680008)
val md_theme_dark_secondaryContainer = Color(color = 0xFF930010)
val md_theme_dark_onSecondaryContainer = Color(color = 0xFFFFDAD6)
val md_theme_dark_tertiary = Color(color = 0xFFFFB963)
val md_theme_dark_onTertiary = Color(color = 0xFF472A00)
val md_theme_dark_tertiaryContainer = Color(color = 0xFF663E00)
val md_theme_dark_onTertiaryContainer = Color(color = 0xFFFFDDB9)
val md_theme_dark_error = Color(color = 0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(color = 0xFF93000A)
val md_theme_dark_onError = Color(color = 0xFF690005)
val md_theme_dark_onErrorContainer = Color(color = 0xFFFFDAD6)
val md_theme_dark_background = Color(color = 0xFF2C1700)
val md_theme_dark_onBackground = Color(color = 0xFFFFDCBB)
val md_theme_dark_surface = Color(color = 0xFF2C1700)
val md_theme_dark_onSurface = Color(color = 0xFFFFDCBB)
val md_theme_dark_surfaceVariant = Color(color = 0xFF52443D)
val md_theme_dark_onSurfaceVariant = Color(color = 0xFFD7C2BA)
val md_theme_dark_outline = Color(color = 0xFFA08D85)
val md_theme_dark_inverseOnSurface = Color(color = 0xFF2C1700)
val md_theme_dark_inverseSurface = Color(color = 0xFFFFDCBB)
val md_theme_dark_inversePrimary = Color(color = 0xFFA14000)
val md_theme_dark_shadow = Color(color = 0xFF000000)
val md_theme_dark_surfaceTint = Color(color = 0xFFFFB694)
val md_theme_dark_outlineVariant = Color(color = 0xFF52443D)
val md_theme_dark_scrim = Color(color = 0xFF000000)


val seed = Color(color = 0xFFFD6900)

val colorGreenDark = Color(color = 0xFF43A047)
val colorGreenLight = Color(color = 0xFFE8F5E9)
val colorRedDark = Color(color = 0xFFE53935)
val colorRedLight = Color(color = 0xFFFFEBEE)
val colorSelectionDark = Color(color = 0xFFF1F8E9)
val colorSelectionLight = Color(color = 0xFFDCEDC8)
