package com.ahmer.accounts.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(color = 0xFF006493)
val md_theme_light_onPrimary = Color(color = 0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(color = 0xFFCAE6FF)
val md_theme_light_onPrimaryContainer = Color(color = 0xFF001E30)
val md_theme_light_secondary = Color(color = 0xFF006876)
val md_theme_light_onSecondary = Color(color = 0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(color = 0xFFA1EFFF)
val md_theme_light_onSecondaryContainer = Color(color = 0xFF001F25)
val md_theme_light_tertiary = Color(color = 0xFF006782)
val md_theme_light_onTertiary = Color(color = 0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(color = 0xFFBBE9FF)
val md_theme_light_onTertiaryContainer = Color(color = 0xFF001F29)
val md_theme_light_error = Color(color = 0xFFBA1A1A)
val md_theme_light_errorContainer = Color(color = 0xFFFFDAD6)
val md_theme_light_onError = Color(color = 0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(color = 0xFF410002)
val md_theme_light_background = Color(color = 0xFFFFFFFF)
val md_theme_light_onBackground = Color(color = 0xFF001F25)
val md_theme_light_surface = Color(color = 0xFFFFFFFF)
val md_theme_light_onSurface = Color(color = 0xFF001F25)
val md_theme_light_surfaceVariant = Color(color = 0xFFDDE3EA)
val md_theme_light_onSurfaceVariant = Color(color = 0xFF41474D)
val md_theme_light_outline = Color(color = 0xFF72787E)
val md_theme_light_inverseOnSurface = Color(color = 0xFFD6F6FF)
val md_theme_light_inverseSurface = Color(color = 0xFF00363F)
val md_theme_light_inversePrimary = Color(color = 0xFF8DCDFF)
val md_theme_light_shadow = Color(color = 0xFF000000)
val md_theme_light_surfaceTint = Color(color = 0xFF006493)
val md_theme_light_outlineVariant = Color(color = 0xFFC1C7CE)
val md_theme_light_scrim = Color(color = 0xFF000000)

val md_theme_dark_primary = Color(color = 0xFF8DCDFF)
val md_theme_dark_onPrimary = Color(color = 0xFF00344F)
val md_theme_dark_primaryContainer = Color(color = 0xFF004B70)
val md_theme_dark_onPrimaryContainer = Color(color = 0xFFCAE6FF)
val md_theme_dark_secondary = Color(color = 0xFF44D8F1)
val md_theme_dark_onSecondary = Color(color = 0xFF00363E)
val md_theme_dark_secondaryContainer = Color(color = 0xFF004E59)
val md_theme_dark_onSecondaryContainer = Color(color = 0xFFA1EFFF)
val md_theme_dark_tertiary = Color(color = 0xFF61D4FF)
val md_theme_dark_onTertiary = Color(color = 0xFF003545)
val md_theme_dark_tertiaryContainer = Color(color = 0xFF004D63)
val md_theme_dark_onTertiaryContainer = Color(color = 0xFFBBE9FF)
val md_theme_dark_error = Color(color = 0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(color = 0xFF93000A)
val md_theme_dark_onError = Color(color = 0xFF690005)
val md_theme_dark_onErrorContainer = Color(color = 0xFFFFDAD6)
val md_theme_dark_background = Color(color = 0xFF001F25)
val md_theme_dark_onBackground = Color(color = 0xFFA6EEFF)
val md_theme_dark_surface = Color(color = 0xFF001F25)
val md_theme_dark_onSurface = Color(color = 0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(color = 0xFF41474D)
val md_theme_dark_onSurfaceVariant = Color(color = 0xFFC1C7CE)
val md_theme_dark_outline = Color(color = 0xFF8B9198)
val md_theme_dark_inverseOnSurface = Color(color = 0xFF001F25)
val md_theme_dark_inverseSurface = Color(color = 0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(color = 0xFF006493)
val md_theme_dark_shadow = Color(color = 0xFF000000)
val md_theme_dark_surfaceTint = Color(color = 0xFF8DCDFF)
val md_theme_dark_outlineVariant = Color(color = 0xFF41474D)
val md_theme_dark_scrim = Color(color = 0xFF000000)


val seed = Color(color = 0xFF03A9F4)

val colorGreenDark = Color(color = 0xFF43A047)
val colorGreenLight = Color(color = 0xFFE8F5E9)
val colorRedDark = Color(color = 0xFFE53935)
val colorRedLight = Color(color = 0xFFFFEBEE)
val colorSelectionDark = Color(color = 0xFFF1F8E9)
val colorSelectionLight = Color(color = 0xFFDCEDC8)
